### ISSUE TITLE
Should we remove "Add a User" options for maintainers from frontend?

### ISSUE THREAD

**Issue by EvitanRelta** [CS3219-AY2324S1/ay2324s1-course-assessment-g23#158]
It's kind of weird to create new users from the table. Like shouldn't u use the signup page for that?

![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g23/assets/35413456/5b8539a8-6f94-415c-8d1e-a882fe6d3848)

**Comment by afiqzu** [comment]
We can remove it once we move on to the Project, I think we added it because of Assignment 2's requirements, where we have to demonstrate CRUD operations for user profile management:

<img width="783" alt="Screenshot 2023-10-11 at 7 46 16 PM" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g23/assets/93078202/b0444a32-9e6d-46b9-be48-5cc067ab34a3">
